# Generated by Django 3.1.2 on 2020-11-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expiredate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='initialamount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='member',
            name='joindate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
