# Generated by Django 3.1.2 on 2020-11-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20201129_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
