# Generated by Django 3.1.2 on 2020-11-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20201129_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='joindate',
            field=models.DateField(),
        ),
    ]
