# Generated by Django 3.1.2 on 2020-12-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_auto_20201129_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
